config/routes.rb
Rails.application.routes.draw do
  resource :session, only: %i[new create update destroy]
  root 'dashboards#show'
  # namespace :api do ||
  #   get 'avatar/:hash', to: 'api#get_avatar'
  # end
  # scope '/api' do
  #   get '/avatar/:hash', to: 'api#get_avatar'
  # end
  get '/api/:hash', to: 'api/avatars#show'

	post 'profile', to: 'users#edit'
  delete 'profile', to: 'users#destroy'
  get 'profile', to: 'users#show'

  resources :phone_numbers, only: %i[new create destroy]
  resources :avatars, only: %i[create destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/avatar.rb
class Avatar < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  has_many :phones, class_name: 'UserPhone', dependent: :delete_all
  has_many :avatars
end

app/models/user_phone.rb
class UserPhone < ApplicationRecord
  belongs_to :user

  validates :number, presence: true

  after_create :generate_hash

  accepts_nested_attributes_for :user

  def confirmed?
    code.nil?
  end

  def update_code
    update_column(:code, Rails.env.production? ? rand(1000..9999) : 1111)
  end

  private

  def generate_hash
    self.md5_hash = Digest::MD5.hexdigest(self.number)
    self.save
  end
end

app/controllers/api/avatars_controller.rb
class Api::AvatarsController < ActionController::Base
  respond_to? :json

  def show
    user_phone = UserPhone.find_by(md5_hash: params[:hash])
    if user_phone
      render :json => {status: 200, data: user_phone}
    else
      render :json => {status: 404, message: 'not found'}
    end
  end
end

app/controllers/api_controller.rb
class ApiController < ActionController::Base
  respond_to? :json

  def get_avatar
    user_phone = UserPhone.find_by(md5_hash: params[:hash])
    if user_phone
      render :json => {status: 200, data: user_phone}
    else
      render :json => {status: 404, message: 'not found'}
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  layout 'application'

  def require_user
    redirect_to new_session_path unless current_user
  end

  def current_user
    @current_user || User.find_by(id: session[:user_id])
  end
  helper_method :current_user
end

app/controllers/avatars_controller.rb
class AvatarsController < ApplicationController
  skip_before_action :verify_authenticity_token
  def create
    current_user.avatars.create(url: params[:url])
  end

  def destroy
  end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  before_action :require_user

  def show
  end
end

app/controllers/phone_numbers_controller.rb
class PhoneNumbersController < ApplicationController
  def create
    @phone_number = current_user.phones.create(phone_params)
  end

  def edit
  end

  def update
  end

  def destroy
  end

  def phone_params
    params.require(:user_phone).permit(:number)
  end
end

app/controllers/sessions_controller.rb
require Rails.root.join( "lib/sms_sender").to_s
class SessionsController < ApplicationController
  def new
  end

  def create
    @phone = UserPhone.find_by(number: phone_params[:number])
    @phone ||= UserPhone.create(phone_params)
    if @phone.valid?
      session[:phone] = @phone.number
      @phone.update_code
      SmsSender.new(@phone.number, @phone.code).send_sms
    else
      render(:new)
    end
  end

  def update
    phone = UserPhone.find_by(code: params[:code], number: session[:phone])
    if phone
      session[:user_id] = phone.user_id
      phone.update(code: nil)
      redirect_to :root
    else
      render :create
    end
  end

  def destroy
  end

  private

  def phone_params
    params.require(:user_phone).permit(:number, user_attributes: [:email])
  end

  def number
    @user ||= UserPhone.new(user_params)
  end
  helper_method :number
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user
  def new
  end

  def create
  end

  def update
  end

  def edit
    @user = current_user
    @user.update_attributes(user_params)
  end

  def show
    @user = current_user
  end

  def destroy
    current_user.destroy
    reset_session
    redirect_to :root
  end

end

private

def user_params
  params.fetch(:user, {}).permit(:email, phones_attributes: [:number])
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/avatars/create.js.slim
|
  alert('TODO')

app/views/dashboards/show.html.slim
h1 Dashboard

input#dropzone type=:file accept='image/*' name='file'
ul data-images=true
  - current_user.avatars.each do |ava|
    li
      img.avatar src=ava.url

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | Avatron
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body
    = yield

app/views/phone_numbers/_form.html.slim
= simple_form_for user_phone, url: phone_numbers_path, method: :post, remote: true do |f|
  = f.input :number
  = f.submit :OK

app/views/phone_numbers/_phone_number.html.slim
li
  => phone_number.number
  button data-url=phone_number_path(phone_number) data-method=:delete data-remote=true x

app/views/phone_numbers/create.html.slim
h1 PhoneNumbers#create
p Find me in app/views/phone_numbers/create.html.slim

app/views/phone_numbers/create.js.slim
|
  document.getElementById('user_phone_form').innerHTML = ''
  li = document.createElement('li')
  li.innerHTML = '#{j(render partial: 'phone_number', object: @phone_number)}'
  document.getElementById('user_phones').appendChild(li)

app/views/phone_numbers/destroy.html.slim
h1 PhoneNumbers#destroy
p Find me in app/views/phone_numbers/destroy.html.slim

app/views/phone_numbers/edit.html.slim
h1 PhoneNumbers#edit
p Find me in app/views/phone_numbers/edit.html.slim

app/views/phone_numbers/new.js.slim
|
  document.getElementById('user_phone_form').innerHTML = '#{j(render('phone_numbers/form', user_phone: UserPhone.new))}'

app/views/phone_numbers/update.html.slim
h1 PhoneNumbers#update
p Find me in app/views/phone_numbers/update.html.slim

app/views/users/_edit.html.slim
= simple_form_for :user do |f|
	= f.input :email
	= f.button :submit, t(:edit_email)

app/views/users/add_number.html.slim
h1 Add phone number to your profile
= simple_form_for :user, method: :post, remote: true do |f|
 = f.simple_fields_for :phones do |p|
   = p.input :number
 = f.submit :OK

app/views/users/show.html.slim
h1= t(:profile_page)

= render 'edit'

ul#user_phones
  = render partial: 'phone_numbers/phone_number', collection: @user.phones

#user_phone_form
button data-url=new_phone_number_path data-remote=true Add phone

= button_to t(:remove_acc), '/profile', method: "delete", remote: true, data: {confirm: 'Are you sure?'}